require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const connectDB = require('./config/db');
const { redirectUrl } = require('./controllers/urlController');
const app = express();
connectDB();
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: process.env.CLIENT_URL, credentials: true }));
app.use(rateLimit({ windowMs: 15*60*1000, max: 200 }));
app.use(express.json({ limit: '10kb' }));
app.get('/api/health', (req, res) => res.json({ status: 'OK', name: 'VΛLTEX API' }));
app.use('/api/auth', require('./routes/authRoutes'));
app.use('/api/urls', require('./routes/urlRoutes'));
app.use('/api/analytics', require('./routes/analyticsRoutes'));
app.get('/:code', redirectUrl);
app.use((req, res) => res.status(404).json({ success: false, message: 'Not found.' }));
app.use((err, req, res, next) => res.status(500).json({ success: false, message: err.message }));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🚀 VΛLTEX running → http://localhost:${PORT}`));
